{% set name = "dedupe" %}
{% set version = "2.0.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dedupe-{{ version }}.tar.gz
  sha256: 31f1d91e1da51a52bac12341d979297a38d38223349ba6fd6f7d17509d871700

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - scikit-learn
    - affinegap >=1.3
    - btrees >=4.1.4
    - categorical-distance >=1.9
    - dedupe-variable-datetime
    - doublemetaphone
    - haversine >=0.4.1
    - highered >=0.2.0
    - levenshtein-search
    - numpy >=1.13
    - python
    - simplecosine >=1.2
    - typing-extensions
    - zope.index

test:
  imports:
    - dedupe
    - dedupe.variables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dedupeio/dedupe
  summary: A python library for accurate and scaleable data deduplication and entity-resolution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
